/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DaftarPendonorRouteImport } from './routes/daftar-pendonor'
import { Route as CariPendonorRouteImport } from './routes/cari-pendonor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as FormFormIdRouteImport } from './routes/form.$formId'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminDonorsRouteImport } from './routes/admin.donors'
import { Route as AdminDatabaseRouteImport } from './routes/admin.database'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'

const DaftarPendonorRoute = DaftarPendonorRouteImport.update({
  id: '/daftar-pendonor',
  path: '/daftar-pendonor',
  getParentRoute: () => rootRouteImport,
} as any)
const CariPendonorRoute = CariPendonorRouteImport.update({
  id: '/cari-pendonor',
  path: '/cari-pendonor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FormFormIdRoute = FormFormIdRouteImport.update({
  id: '/form/$formId',
  path: '/form/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonorsRoute = AdminDonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDatabaseRoute = AdminDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cari-pendonor': typeof CariPendonorRoute
  '/daftar-pendonor': typeof DaftarPendonorRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/donors': typeof AdminDonorsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/form/$formId': typeof FormFormIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cari-pendonor': typeof CariPendonorRoute
  '/daftar-pendonor': typeof DaftarPendonorRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/donors': typeof AdminDonorsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/form/$formId': typeof FormFormIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cari-pendonor': typeof CariPendonorRoute
  '/daftar-pendonor': typeof DaftarPendonorRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/donors': typeof AdminDonorsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/form/$formId': typeof FormFormIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cari-pendonor'
    | '/daftar-pendonor'
    | '/admin/announcements'
    | '/admin/articles'
    | '/admin/cms'
    | '/admin/database'
    | '/admin/donors'
    | '/admin/forms'
    | '/admin/gallery'
    | '/admin/requests'
    | '/form/$formId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cari-pendonor'
    | '/daftar-pendonor'
    | '/admin/announcements'
    | '/admin/articles'
    | '/admin/cms'
    | '/admin/database'
    | '/admin/donors'
    | '/admin/forms'
    | '/admin/gallery'
    | '/admin/requests'
    | '/form/$formId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cari-pendonor'
    | '/daftar-pendonor'
    | '/admin/announcements'
    | '/admin/articles'
    | '/admin/cms'
    | '/admin/database'
    | '/admin/donors'
    | '/admin/forms'
    | '/admin/gallery'
    | '/admin/requests'
    | '/form/$formId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CariPendonorRoute: typeof CariPendonorRoute
  DaftarPendonorRoute: typeof DaftarPendonorRoute
  FormFormIdRoute: typeof FormFormIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/daftar-pendonor': {
      id: '/daftar-pendonor'
      path: '/daftar-pendonor'
      fullPath: '/daftar-pendonor'
      preLoaderRoute: typeof DaftarPendonorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cari-pendonor': {
      id: '/cari-pendonor'
      path: '/cari-pendonor'
      fullPath: '/cari-pendonor'
      preLoaderRoute: typeof CariPendonorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/form/$formId': {
      id: '/form/$formId'
      path: '/form/$formId'
      fullPath: '/form/$formId'
      preLoaderRoute: typeof FormFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donors': {
      id: '/admin/donors'
      path: '/donors'
      fullPath: '/admin/donors'
      preLoaderRoute: typeof AdminDonorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/database': {
      id: '/admin/database'
      path: '/database'
      fullPath: '/admin/database'
      preLoaderRoute: typeof AdminDatabaseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminDatabaseRoute: typeof AdminDatabaseRoute
  AdminDonorsRoute: typeof AdminDonorsRoute
  AdminFormsRoute: typeof AdminFormsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminArticlesRoute: AdminArticlesRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminDatabaseRoute: AdminDatabaseRoute,
  AdminDonorsRoute: AdminDonorsRoute,
  AdminFormsRoute: AdminFormsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CariPendonorRoute: CariPendonorRoute,
  DaftarPendonorRoute: DaftarPendonorRoute,
  FormFormIdRoute: FormFormIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
